### PR TITLE
gitTranslating first article

### PR DESCRIPTION
**Pull request by cybercitizen7**

### CODE REVIEW

**Comment by cybercitizen7** [comment]
Can be merged.

**Comment by cybercitizen7** [comment]
@iliakan Could you please check permissions on this Project? I cannot Approve my own Pull Requests. Since I am currently the only contributor, this would need to be sorted out. Or did I miss something?

**Comment by iliakan** [comment]
Can you merge PRs?

**Comment by cybercitizen7** [comment]
> Can you merge PRs?

Unfortunately, I cannot. "Only those with write access to this repository can merge pull requests." @iliakan

**Comment by iliakan** [comment]
Did you get the invite and joined the org?

**Comment by cybercitizen7** [comment]
That was it @iliakan , I thought I did press Accept to join, but it seems i did not. Now I see the ability to Merge the PR. Thanks!

**Pull request merged**
